<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8" />';
echo '<meta name="description" content="Area and Perimeter, with JavaScript" />';
echo '<meta name="keywords" content="immaculata, ics2o" />';
echo '<meta name="author" content="Brayden MacMillan" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0" />';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />';
echo '<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-purple.min.css" />';
echo '<link rel="stylesheet" href="./css/style.css" />';
echo '<title>Area of a triangle, with PHP</title>';
echo '</head>';
echo '<body>';
echo '<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>';
echo '<script src="./js/script.js"></script>';
echo '<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">';
echo '<header class="mdl-layout__header">';
echo '<div class="mdl-layout__header-row">';
echo '<span class="mdl-layout-title">Area of a triangle with PHP</span>';
echo '</div>';
echo '</header>';
echo '<main class="mdl-layout__content">';
echo '<table>';
echo '<tr>';
echo '<th>';
echo '<img src="./images/triangle.jpg" alt="triangle" width="75%" height="auto"/>';
echo '</th>';
echo '<th>';
echo '<h2>Formulas</h2>';
echo '<h3>A = (B x H) ÷ 2</h3>';
echo '</th>';
echo '</tr>';
echo '</table>';
echo '<!-- Simple Textfield -->';
echo '<form action="#">';
echo '<p>Base</p>';
echo '<div class="mdl-textfield mdl-js-textfield">';
echo '<input';
echo 'class="mdl-textfield__input"';
echo 'type="text"';
echo 'pattern="-?[0-9]*(\.[0-9]+)?"';
echo 'id="base-of-rectangle"';
echo '/>';
echo '<label class="mdl-textfield__label" for="base-of-rectangle">base ...</label>';
echo '<span class="mdl-textfield__error">Input is not a number!</span>';
echo '</div>';
echo '</form>';
echo '';
echo '<!-- Numeric Textfield -->';
echo '<form action="#">';
echo '<p>Height</p>';
echo '<div class="mdl-textfield mdl-js-textfield">';
echo '<input';
echo 'class="mdl-textfield__input"';
echo 'type="text"';
echo 'pattern="-?[0-9]*(\.[0-9]+)?"';
echo 'id="height-of-rectangle"';
echo '/>';
echo '<label class="mdl-textfield__label" for="height-of-rectangle">height ...</label>';
echo '<span class="mdl-textfield__error">Input is not a number!</span>';
echo '</div>';
echo '</form>';
echo '';
echo '<!-- Raised button with ripple -->';
echo '<button';
echo 'class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"';
echo 'onclick="calculate()"';
echo '>';
echo 'Calculate';
echo '</button>';
echo '<br />';
echo '<p>';
echo '<div id="answers">';
echo '<div id="area"></div>';
echo '<div id="perimeter"></div>';
echo '</div>';
echo '</p>';
echo '</main>';
echo '</div>';
echo '</body>';
echo '</html>';
?>